apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops_app.fullname" . }}-app
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops_app.name" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "devops_app.name" . }}-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: MONGO_URI
              value: "mongodb://{{ .Values.mongo.mongoRootUsername }}:{{ .Values.mongo.mongoRootPassword }}@{{ include "devops_app.fullname" . }}-mongo:27017/admin"
