apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops_app.fullname" . }}-app
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.service.internalPort }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.service.nodePort }}
  selector:
    app: {{ include "devops_app.name" . }}
