apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops_app.fullname" . }}-grafana
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: {{ .Values.grafana.port }}
      nodePort: {{ .Values.grafana.service.nodePort }}
  selector:
    app: {{ include "devops_app.name" . }}-grafana
