apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops_app.fullname" . }}-grafana
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "devops_app.name" . }}-grafana
  template:
    metadata:
      labels:
        app: {{ include "devops_app.name" . }}-grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image }}:{{ .Values.grafana.tag }}"
          ports:
            - containerPort: {{ .Values.grafana.port }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc


