apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: grafana-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/grafana" 
