apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops_app.fullname" . }}-mongo
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "devops_app.name" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "devops_app.name" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
