apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops_app.fullname" . }}-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: '{{ include "devops_app.name" . }}-app'
        static_configs:
          - targets: ['{{ include "devops_app.fullname" . }}-app:5000']
      - job_name: '{{ include "devops_app.name" . }}-mongo'
        static_configs:
          - targets: ['{{ include "devops_app.fullname" . }}-mongo:27017']
