apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops_app.fullname" . }}-prometheus
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.prometheus.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "devops_app.name" . }}-prometheus
