apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops_app.fullname" . }}-prometheus
  labels:
    {{- include "devops_app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "devops_app.name" . }}-prometheus
  template:
    metadata:
      labels:
        app: {{ include "devops_app.name" . }}-prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image }}:{{ .Values.prometheus.tag }}"
          ports:
            - containerPort: {{ .Values.prometheus.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops_app.fullname" . }}-prometheus-config
