# Values for  application
app:
  image: "moustafaroushdy/app"
  tag: "latest"
  port: 5000
  environment:
    MONGO_URI: "mongodb://mongo:27017/admin"

# Values for MongoDB
mongo:
  image: "mongo"
  tag: "latest"
  port: 27017
  mongoRootUsername: "root"
  mongoRootPassword: "password"

# Values for Prometheus
prometheus:
  image: "prom/prometheus"
  tag: "latest"
  port: 9090
  configMap:
    enabled: true

# Values for Grafana
grafana:
  image: "grafana/grafana"
  tag: "latest"
  port: 3000
  adminPassword: "admin"

# Persistent Volume Claims
persistence:
  enabled: true
  size: 1Gi
